sudo: required
language: generic

services:
  - docker       #install docker

before_install:
    #can use any tag but convention is <github login> / <repository name> 
        - docker build -t lavendermd/docker-react -f Dockerfile.dev .

#script contains all commands that need to be executed to run test suite
script:
  - docker run -e CI=true lavendermd/docker-react npm run test -- --coverage
    # coverage displays code coverage (#lines)
    # -- tells npm run test to exit after finished

